---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-UTC}
    volumes:
      - ${BASE}/config:/config
      - ${MEDIA}/shows:/tv #optional
      - ${CLIENT}/downloads:/downloads #optional
    ports:
      - ${WEB_UI}:8989
    restart: unless-stopped
