---
services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports: #make sure to include these for qbittorrent to work
      - ${TCP_PORT}:${TCP_PORT}
      - ${TCP_PORT}:${TCP_PORT}/udp
      - ${WEB_UI}:${WEB_UI}
    dns:
       - ${DNS_IP}
       - ${SECONDARY_DNS_IP}
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIV_KEY}
      - WIREGUARD_ADDRESSES=${WIRE_ADDRS}
      - SERVER_CITIES=${CITY} #choose any available city
    volumes:
      - ${BASE}/gluetun:/gluetun
    restart: unless-stopped

# For the first use, a temporary password is provided to login.
# To log in for the first time, use the local IP address of the host.
# Do not use the DNS hostname. For whatever reason, it cannot
# authenticate.
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=${WEB_UI}
    volumes:
      - ${BASE}/config:/config
      - ${BASE}/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped
