---
####################################################################
#                       MINECRAFT SERVER                           #
####################################################################
services:

####################################################################
#                         Service Name                             #
#                                                                  #
# Define Service Name here. If using RCON this name will be        #
# referenced again as RWA_RCON_HOST below.                         #
#                                                                  #
# Example: 'name:' or 'mc_atm6:'                                   #
####################################################################
   modpack_landscapes-reimagined-genesis:

####################################################################
#                      Image & Container Name                      #
#                                                                  #
# Specify Image Name and Java Version. The 'image' will always be  #
# 'itzg/minecraft-server' however the tag added to the end is      #
# where you can specify the java version or container architecture.#
# See readme.md for a full list.                                   #
#                                                                  #
# 'container_name:' This can be anything you like. This is the     #
# name that will show when you run 'docker ps' commands.           #
####################################################################
      image: itzg/minecraft-server:latest
      container_name: modpack_landscapes-reimagined-genesis

####################################################################
#                         Server Ports                             #
#                                                                  #
# Specify external port.                                           #
####################################################################
      ports:
         - ${MC_PORT_HOST}:${MC_PORT_DOCKER}
      dns:
         - 8.8.8.8

####################################################################
#                   Automatic Server Restart                       #
#                                                                  #
# Define a restart policy here.                                    #
#    - 'no' = Do not restart.                                      #
#    - 'on-failure' = Restart if container exits because an error. #
#    - 'always' = Regardless of stop reason.                       #
#    - 'unless-stopped' = Similar to always except if stopped.     #
####################################################################
      restart: unless-stopped

####################################################################
#                     Volume and Folder Access                     #
#                                                                  #
# This section defines what folders and volumes you want to give   #
# this container access to. It is recommended to leaves these set  #
# to the default values unless you know what you are doing.        #
####################################################################
      volumes:
         - minecraftdata_modpack_landscapes-reimagined-genesis:/data

####################################################################
#                             EULA                                 #
#                                                                  #
# Accept EULA by setting to "true"                                 #
####################################################################
      environment:
         EULA: "TRUE"

####################################################################
#                       CONTAINER USER                             #
#                                                                  #
# Sets the default user to run the container                       #
####################################################################
         PUID: 1000
         PGID: 1000

####################################################################
#                       MINECRAFT VERSION                          #
#                                                                  #
# Sets the Minecraft version                                       #
####################################################################
         VERSION: 1.20.1

####################################################################
#                           MODPACK                                #
#                                                                  #
# Add a "slug" to the modpack you would like to use:               #
####################################################################
         MOD_PLATFORM: MODRINTH
         MODRINTH_LOADER: "fabric"
         MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
         MODRINTH_MODPACK: landscapes-reimagined-genesis

####################################################################
#                          Server Memory                           #
#                                                                  #
# Set Maximum amount of memory allowed for your server.            #
####################################################################
         MEMORY: "8G"

####################################################################
#                         Logging Options                          #
#                                                                  #
# Set to "true" to delete old logs                                 #
####################################################################
         ENABLE_ROLLING_LOGS: "true"

####################################################################
#                          Server Timezone                         #
#                                                                  #
# Specify server Timezone                                          #
####################################################################
         TZ: ${TZ:-UTC}

####################################################################
#                       Minecraft Game Options                     #
#                                                                  #
# List any game options you want to define here.                   #
####################################################################
         OVERRIDE_SERVER_PROPERTIES: "true"
         ALLOW_FLIGHT: "true"
         DIFFICULTY: "normal"
         ENABLE_WHITELIST: "true"
         ENFORCE_WHITELIST: "true"
         ICON: https://cdn.modrinth.com/data/MdznSbKA/5b106d3f8e7f42ab1613e1b6f08da918d2c6eb90_96.webp
         MAX_PLAYERS: 10
         MAX_TICK_TIME: "-1"
         OPS: ${OP_USER}
         MAX_CHAINED_NEIGHBOR_UPDATES: 10000
         MOTD: ${MOTD}
         SEED: ${SEED}
         VIEW_DISTANCE: 8
         SIMULATION_DISTANCE: 6
         SYNC_CHUNK_WRITES: "false"

####################################################################
#                       Misc Options                               #
####################################################################
      tty: true
      stdin_open: true
####################################################################
#                            Volumes                               #
#                                                                  #
# Define data volume name here. This will be where the world lives #
# and what will be backed up.                                      #
####################################################################
volumes:
   minecraftdata_modpack_landscapes-reimagined-genesis:
      external: true
