---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${BASE}/config:/config
      - ${MEDIA}/books:/books #optional
      - ${CLIENT}/downloads:/downloads #optional
    ports:
      - ${WEB_UI}:8787
    restart: unless-stopped
