---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${BASE}/config:/config
    ports:
      - ${HOST_PORT}:${DOCK_PORT}
    restart: unless-stopped