version: "3"

####################################################################
#                 CURSEFORGE_GENERIC_MODPACK                       #
#                                                                  #
# Date: 2022-12-21                                                 #
#                                                                  #
# Mod: Better Minecraft Plus FABRIC v12.5                          #
#                                                                  #
# Game Version: 1.19.2                                             #
#                                                                  #
# Notes: Verify that there is no EULA file in the modpack.zip      #
#        if you do not delete it the EULA flag below will be       #
#        overwritten when the modpack is copied.                   #
#                                                                  #
####################################################################
services:

####################################################################
#                         Service Name                             #
#                                                                  #
# Define Service Name here. If using RCON this name will be        #
# referenced again as RWA_RCON_HOST below.                         #
#                                                                  #
# Example: 'name:' or 'mc_atm6:'                                   #
####################################################################
  mc_bmc_fabric_1:

####################################################################
#                      Image & Container Name                      #
#                                                                  #
# Specify Image Name and Java Version. The 'image' will always be  #
# 'itzg/minecraft-server' however the tag added to the end is      #
# where you can specify the java version or container architecture.#
# See readme.md for a full list.                                   #
#                                                                  #
# 'container_name:' This can be anything you like. This is the name#
# that will show when you run 'docker ps' commands.                #
####################################################################
    image: itzg/minecraft-server
    container_name: mc_bmc_fabric_1

####################################################################
#                         Server Ports                             #
#                                                                  #
# Specify external port.                                           #
####################################################################
    ports:
      - ${MC_HOST_PORT}:${MC_DOCKER_PORT}

####################################################################
#                   Automatic Server Restart                       #
#                                                                  #
# Define a restart policy here.                                    #
#    - 'no' = Do not restart.                                      #
#    - 'on-failure' = Restart if container exits because an error. #
#    - 'always' = Regardless of stop reason.                       #
#    - 'unless-stopped' = Similar to always except if stopped.     #
####################################################################
    restart: unless-stopped

####################################################################
#                     Volume and Folder Access                     #
#                                                                  #
# This section defines what folders and volumes you want to give   #
# this container access to. It is recommended to leaves these set  #
# to the default values unless you know what you are doing.        #
#                                                                  #
# Place your mod zip file in a folder called 'modpacks' in the     #
# same directory you place this docker-compose file.               #
#                                                                  #
# Specify the data volume name or directory here as well.          #
# In this example the volume name is 'data'. When docker creates   #
# the volume it will add what ever name you give it here to the    #
# end of the container name specified above. In this example it    #
# would be named 'mc_atm6_data'. If you change this be sure to     #
# update the volume name at the bottom of this config.             #
####################################################################
    volumes:
      - minecraft_better_minecraft_fabric_data:/data

####################################################################
#                             EULA                                 #
#                                                                  #
# Accept EULA by setting to "true"                                 #
####################################################################
    environment:
      EULA: "TRUE"

####################################################################
#                       CONTAINER USER                             #
#                                                                  #
# Sets the default user to run the container                       #
# (Not ideal, but it seems the docker's root must run it)          #
####################################################################
      UID: 0
      GID: 0

####################################################################
#                       MINECRAFT VERSION                          #
#                                                                  #
# Sets the Minecraft version the modpack should be built against   #
####################################################################
      VERSION: 1.19.2

####################################################################
#                    CURSEFORGE MODPACK INSTALL                    #
#                                                                  #
# Sets install type to CURSEFORGE and specifys the zip folder name #
# and location of your mod pack.                                   #
#                                                                  #
# TYPE: Defines the install type as CURSEFORGE                     #
#                                                                  #
# CF_SERVER_MOD: Defines where the CURSEFORGE server modpack.zip   #
#                is located                                        #
#                                                                  #
# CF_BASE_DIR: The base directory for where the server instance    #
#              is located                                          #
#                                                                  #
# Place your mod zip file in a folder called 'modpacks' in the     #
# same directory you place this docker-compose file.               #
####################################################################
      TYPE: AUTO_CURSEFORGE
      CF_SERVER_MOD: ${BETTER_MC_FABRIC_ZIP}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/better-mc-fabric
      CF_API_KEY: ${CF_API_KEY}

####################################################################
#                          Server Memory                           #
#                                                                  #
# Set Maximum amount of memory allowed for your server.            #
####################################################################
      MEMORY: "8G"

####################################################################
#                         Logging Options                          #
#                                                                  #
# Set to "true" to delete old logs                                 #
####################################################################
      ENABLE_ROLLING_LOGS: "true"

####################################################################
#                          Server Timezone                         #
#                                                                  #
# Specify server Timezone                                          #
####################################################################
      TZ: "America/Chicago"

####################################################################
#                       Minecraft Game Options                     #
#                                                                  #
# List any game options you want to define here. A full list can   #
# be found on the readme.md page on github.                        #
####################################################################
      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "normal"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      OPS: ${OP_USER}
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10
      PVP: "false"
      LEVEL_TYPE: "biomesoplenty"
      MOTD: "Better MC [FABRIC] 1.19.2 v17.5"

    tty: true
    stdin_open: true
####################################################################
#                            Volumes                               #
#                                                                  #
# Define data volume name here. This will be where the world lives #
# and what will be backed up.                                      #
####################################################################
volumes:
  minecraft_better_minecraft_fabric_data:
    external: true
