---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-UTC}
    volumes:
      - ${BASE}/config:/config
      - ${MEDIA}/movies:/movies #optional
      - ${CLIENT}/downloads:/downloads #optional
    ports:
      - ${WEB_UI}:7878
    restart: unless-stopped
