---
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${BASE}/configs:/app/data/configs
      - ${BASE}/icons:/app/public/icons
      - ${BASE}/data:/data
    ports:
      - ${WEB_UI}:${WEB_UI}
    restart: unless-stopped