---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - ${CONFIG}:/config
      - ${TORRENT_BLACKHOLE}:/downloads
    ports:
      - ${WEB_UI}:9117
    restart: unless-stopped