---
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "${WEB_UI}:8080" # webapp
      - "${DB_PORT}:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${CONFIG}:/opt/scrutiny/config
      - ${DB}:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"