---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${BASE}/config:/config
      - ${BASE}/cache:/cache
      - ${MEDIA}/shows:/data/tvshows
      - ${MEDIA}/shows-4k:/data/tvshows-4k
      - ${MEDIA}/movies:/data/movies
      - ${MEDIA}/movies-4k:/data/movies-4k
      - ${MEDIA}/music:/data/music
    ports:
      - ${HOST_PORT}:8096
      - ${JELLY_UDP_PORT}:7359/udp
    networks:
      - nginx_default
    restart: unless-stopped

networks:
  nginx_default:
      external: true
      name: nginx_default