---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - JELLYFIN_PublishedServerUrl=${JELLY_SERVER}
    volumes:
      - ${CONFIG_DIR}:/config
      - ${CACHE_DIR}:/cache
      - ${SHOWS_DIR}:/data/tvshows
      - ${SHOWS_DIR_4K}:/data/tvshows-4k
      - ${MOVIES_DIR}:/data/movies
      - ${MOVIES_DIR_4K}:/data/movies-4k
      - ${MUSIC_DIR}:/data/music
    ports:
      - ${JELLY_PORT}:8096
      - ${JELLY_UDP_PORT}:7359/udp
#      - 1900:1900/udp #optional
    restart: unless-stopped
