version: '3.3'
services:
    transmission-openvpn:
      image: haugene/transmission-openvpn
      container_name: transmission-openvpn
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - UMASK=002
        - OPENVPN_PROVIDER=NORDVPN
        - NORDVPN_COUNTRY=US
        - NORDVPN_CATEGORY=legacy_p2p
        - NORDVPN_PROTOCOL=udp
        - OPENVPN_USERNAME=${USERNAME_VPN}
        - OPENVPN_PASSWORD=${PW_VPN}
        - LOCAL_NETWORK=192.168.1.0/24
        - TZ=${TZ:-UTC}
        - TRANSMISSION_WEB_UI=transmission-web-control
        - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
        - USER=${USERNAME_TR} #optional
        - PASS=${PW_TR} #optional
        - PEERPORT=${TORRENT_PORT} #optional
      volumes:
        - ${TRANSMISSION_BASE}/config:/config
        - ${TRANSMISSION_BASE}/data:/data
        - ${TRANSMISSION_BASE}/watch:/watch
      logging:
        driver: json-file
        options:
          max-size: 10m
      ports:
        - ${WEB_UI}:9091
        - ${TORRENT_PORT}:51413
        - ${TORRENT_PORT}:51413/udp
      restart: unless-stopped
