---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ:-UTC}
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
      - USER=${USERNAME} #optional
      - PASS=${PW} #optional
      - PEERPORT=${TORRENT_PORT} #optional
    volumes:
      - ${TRANSMISSION_BASE}/config:/config
      - ${TRANSMISSION_BASE}/downloads:/downloads
      - ${TRANSMISSION_BASE}/watch:/watch
    ports:
      - ${WEB_UI}:9091
      - ${TORRENT_PORT}:51413
      - ${TORRENT_PORT}:51413/udp
    restart: unless-stopped
