---
####################################################################
#                   MINECRAFT VANILLA SERVER                       #
####################################################################
services:

####################################################################
#                         Service Name                             #
#                                                                  #
# Define Service Name here. If using RCON this name will be        #
# referenced again as RWA_RCON_HOST below.                         #
#                                                                  #
# Example: 'name:' or 'mc_atm6:'                                   #
####################################################################
  mc-vanilla:

####################################################################
#                      Image & Container Name                      #
#                                                                  #
# Specify Image Name and Java Version. The 'image' will always be  #
# 'itzg/minecraft-server' however the tag added to the end is      #
# where you can specify the java version or container architecture.#
# See readme.md for a full list.                                   #
#                                                                  #
# 'container_name:' This can be anything you like. This is the name#
# that will show when you run 'docker ps' commands.                #
####################################################################
    image: itzg/minecraft-server:latest
    container_name: mc-vanilla
    tty: true
    stdin_open: true

####################################################################
#                         Server Ports                             #
#                                                                  #
# Specify external port.                                           #
####################################################################
    dns:
      - 1.1.1.1

####################################################################
#                   Automatic Server Restart                       #
#                                                                  #
# Define a restart policy here.                                    #
#    - 'no' = Do not restart.                                      #
#    - 'on-failure' = Restart if container exits because an error. #
#    - 'always' = Regardless of stop reason.                       #
#    - 'unless-stopped' = Similar to always except if stopped.     #
####################################################################
    restart: unless-stopped

####################################################################
#                     Volume and Folder Access                     #
#                                                                  #
# This section defines what folders and volumes you want to give   #
# this container access to. It is recommended to leaves these set  #
# to the default values unless you know what you are doing.        #
####################################################################
    volumes:
      - minecraftdata_vanilla:/data

####################################################################
#                             EULA                                 #
#                                                                  #
# Accept EULA by setting to "true"                                 #
####################################################################
    environment:
      EULA: "TRUE"

####################################################################
#                       CONTAINER USER                             #
#                                                                  #
# Sets the default user to run the container                       #
####################################################################
      PUID: 1000
      PGID: 1000

####################################################################
#                       MINECRAFT VERSION                          #
#                                                                  #
# Sets the Minecraft version                                       #
####################################################################
      VERSION: "LATEST"

####################################################################
#                           SERVER TYPE                            #
####################################################################
      TYPE: "PAPER"

####################################################################
#                           PLUGINS                                #
#                                                                  #
# Add URLs to the plugins you would like to use:                   #
####################################################################
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.22.0-dev+19-7bc91f1.jar
        https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsXSpawn-2.22.0-dev+19-7bc91f1.jar
        https://www.spigotmc.org/resources/f3nperm.46461/download?version=590683
        https://www.spigotmc.org/resources/luckperms.28140/download?version=590885
        https://github.com/ViaVersion/ViaVersion/releases/download/5.4.2/ViaVersion-5.4.2.jar
        https://github.com/ViaVersion/ViaBackwards/releases/download/5.4.2/ViaBackwards-5.4.2.jar
        https://dev.bukkit.org/projects/worldedit/files/latest
        https://dev.bukkit.org/projects/worldguard/files/latest

####################################################################
#                          Server Memory                           #
#                                                                  #
# Set Maximum amount of memory allowed for your server.            #
####################################################################
      MEMORY: "4G"

####################################################################
#                         Logging Options                          #
#                                                                  #
# Set to "true" to delete old logs                                 #
####################################################################
      ENABLE_ROLLING_LOGS: "true"

####################################################################
#                          Server Timezone                         #
#                                                                  #
# Specify server Timezone                                          #
####################################################################
      TZ: ${TZ:-UTC}

####################################################################
#                       Minecraft Game Options                     #
#                                                                  #
# List any game options you want to define here.                   #
####################################################################
      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "normal"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      ICON: ${ICON}
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      OPS: ${OP_USER}
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10
      MOTD: ${MOTD}
      SEED: ${SEED}

####################################################################
#                            Volumes                               #
#                                                                  #
# Define data volume name here. This will be where the world lives #
# and what will be backed up.                                      #
####################################################################
volumes:
  minecraftdata_vanilla:
    external: true
