---
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=${TZ:-UTC}
       ports:
            - ${WEB_UI}:5055
       volumes:
            - ${BASE}/config:/app/config
       restart: unless-stopped

volumes:
  jellyseerr-data:
    external: true